name: Yaml Lint
on: [push, pull_request]
jobs:
  validateLanguageFiles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@master
      with:
        file_or_dir: ./src/lang/
        config_file: .yamllint.yml
        strict: false
